use crate::vibehub::current;
use anyhow::{anyhow, Context, Result};
use chrono::{SecondsFormat, Utc};
use serde::Serialize;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct HandoffBuildResult {
    pub handoff_path: String,
    pub source_output_path: Option<String>,
    pub complete: bool,
    pub missing_required_sections: Vec<String>,
    pub files_changed_evidence: String,
    pub task_id: String,
    pub run_id: String,
    pub session_id: Option<String>,
}

#[derive(Debug, Clone)]
struct HandoffInput {
    task_id: String,
    run_id: String,
    phase: String,
    session_id: Option<String>,
    source_output_path: Option<String>,
    sections: BTreeMap<String, String>,
    git_changed_files: Option<Vec<String>>,
}

const REQUIRED_SECTIONS: &[(&str, &str)] = &[
    ("Completed", "completed"),
    ("Not Yet Done", "not yet done"),
    ("Key Decisions Made", "key decisions made"),
    ("Files Changed", "files changed"),
    ("Files Reportedly Read", "files reportedly read"),
    ("Context Still Needed", "context still needed"),
    ("Warnings", "warnings"),
    ("Next Session Should", "next session should"),
];

pub fn build_handoff(project_root: impl AsRef<Path>) -> Result<HandoffBuildResult> {
    let project_root = canonical_project_root(project_root.as_ref())?;
    let task_pointer = current::resolve_current_task(&project_root)?;
    let run_pointer = current::resolve_current_run(&project_root, &task_pointer.task_id)?;
    let output = find_latest_session_output(&project_root, &run_pointer.path)?;
    let sections = match &output {
        Some((_, path)) => parse_output_sections(path)?,
        None => BTreeMap::new(),
    };
    let phase = read_current_phase(&project_root).unwrap_or_else(|| "unknown".to_string());
    let git_changed_files = git_changed_files(&project_root);
    let source_output_path = output
        .as_ref()
        .map(|(_, path)| relative_to_project(&project_root, path).map(|path| normalize_path(&path)))
        .transpose()?;
    let session_id = output.as_ref().map(|(session_id, _)| session_id.clone());
    let input = HandoffInput {
        task_id: task_pointer.task_id,
        run_id: run_pointer.run_id,
        phase,
        session_id,
        source_output_path,
        sections,
        git_changed_files,
    };

    let missing_required_sections = missing_required_sections(&input);
    let complete = missing_required_sections.is_empty();
    let agent_view_dir = project_root.join(".vibehub/agent-view");
    fs::create_dir_all(&agent_view_dir)
        .with_context(|| format!("Failed to create {}", agent_view_dir.display()))?;
    let handoff_path = agent_view_dir.join("handoff.md");
    fs::write(
        &handoff_path,
        render_handoff(&input, complete, &missing_required_sections),
    )
    .with_context(|| format!("Failed to write {}", handoff_path.display()))?;

    Ok(HandoffBuildResult {
        handoff_path: normalize_path(&relative_to_project(&project_root, &handoff_path)?),
        source_output_path: input.source_output_path,
        complete,
        missing_required_sections,
        files_changed_evidence: if input.git_changed_files.is_some() {
            "hard_observed".to_string()
        } else {
            "agent_reported".to_string()
        },
        task_id: input.task_id,
        run_id: input.run_id,
        session_id: input.session_id,
    })
}

fn render_handoff(input: &HandoffInput, complete: bool, missing: &[String]) -> String {
    let mut output = String::new();
    output.push_str(&format!(
        "# Handoff from Session {}\n\n",
        input.session_id.as_deref().unwrap_or("unknown")
    ));
    output.push_str(&format!("Task: {}  \n", input.task_id));
    output.push_str(&format!("Run: {}  \n", input.run_id));
    output.push_str(&format!("Phase: {}  \n", title_case(&input.phase)));
    output.push_str("Generated by: VibeHub  \n");
    output.push_str(&format!(
        "Generated at: {}  \n",
        Utc::now().to_rfc3339_opts(SecondsFormat::Secs, true)
    ));
    output.push_str(&format!(
        "Source: {}  \n",
        input
            .source_output_path
            .as_deref()
            .unwrap_or("missing session output.md")
    ));
    output.push_str(&format!(
        "Handoff complete: {}  \n",
        if complete { "yes" } else { "no" }
    ));
    output.push_str("Evidence grade: mixed\n\n");

    if !missing.is_empty() {
        output.push_str("## Missing Required Sections\n\n");
        for section in missing {
            output.push_str(&format!("- {}\n", section));
        }
        output.push('\n');
    }

    for (title, key) in REQUIRED_SECTIONS {
        output.push_str(&format!("## {}\n\n", title));
        if *key == "files changed" {
            push_files_changed(&mut output, input);
        } else {
            push_reported_section(&mut output, input, key, title);
            output.push_str("\nEvidence grade: agent_reported\n");
        }
        output.push('\n');
    }

    output
}

fn push_files_changed(output: &mut String, input: &HandoffInput) {
    match &input.git_changed_files {
        Some(files) if files.is_empty() => {
            output.push_str("- No changed files observed by Git.\n\n");
            output.push_str("Evidence grade: hard_observed\n");
        }
        Some(files) => {
            for file in files {
                output.push_str(&format!("- {}\n", file));
            }
            output.push_str("\nEvidence grade: hard_observed\n");
        }
        None => {
            push_reported_section(output, input, "files changed", "Files Changed");
            output.push_str("\nEvidence grade: agent_reported\n");
        }
    }
}

fn push_reported_section(output: &mut String, input: &HandoffInput, key: &str, title: &str) {
    match input.sections.get(key).map(|value| value.trim()) {
        Some(value) if !value.is_empty() => output.push_str(value),
        _ => output.push_str(&format!("- Missing from output.md: {}\n", title)),
    }
}

fn missing_required_sections(input: &HandoffInput) -> Vec<String> {
    REQUIRED_SECTIONS
        .iter()
        .filter_map(|(title, key)| {
            if *key == "files changed" && input.git_changed_files.is_some() {
                return None;
            }
            let present = input
                .sections
                .get(*key)
                .map(|value| !value.trim().is_empty())
                .unwrap_or(false);
            if present {
                None
            } else {
                Some((*title).to_string())
            }
        })
        .collect()
}

fn parse_output_sections(path: &Path) -> Result<BTreeMap<String, String>> {
    let content =
        fs::read_to_string(path).with_context(|| format!("Failed to read {}", path.display()))?;
    let mut sections = BTreeMap::new();
    let mut current_key: Option<String> = None;
    let mut current_lines = Vec::new();

    for line in content.lines() {
        if let Some(title) = markdown_heading_title(line) {
            if let Some(next_key) = canonical_section_key(title) {
                if let Some(key) = current_key.take() {
                    sections.insert(key, current_lines.join("\n").trim().to_string());
                    current_lines.clear();
                }
                current_key = Some(next_key);
            } else if current_key.is_some() {
                current_lines.push(line.to_string());
            }
        } else if current_key.is_some() {
            current_lines.push(line.to_string());
        }
    }

    if let Some(key) = current_key {
        sections.insert(key, current_lines.join("\n").trim().to_string());
    }

    Ok(sections)
}

fn markdown_heading_title(line: &str) -> Option<&str> {
    let trimmed = line.trim_start();
    let hashes = trimmed.chars().take_while(|ch| *ch == '#').count();
    if !(2..=6).contains(&hashes) {
        return None;
    }
    let rest = &trimmed[hashes..];
    if !rest.starts_with(' ') {
        return None;
    }
    Some(rest.trim())
}

fn canonical_section_key(title: &str) -> Option<String> {
    let normalized = normalize_heading(title);
    let key = match normalized.as_str() {
        "completed" => "completed",
        "not yet done" => "not yet done",
        "key decisions made" | "key decisions" => "key decisions made",
        "files changed" | "changed files" => "files changed",
        "files reportedly read" | "files read" => "files reportedly read",
        "context still needed" | "missing context" => "context still needed",
        "warnings" | "unresolved risks" => "warnings",
        "next session should" | "handoff notes" => "next session should",
        _ => return None,
    };
    Some(key.to_string())
}

fn normalize_heading(value: &str) -> String {
    let mut normalized = String::new();
    let mut previous_space = false;
    for ch in value.to_lowercase().chars() {
        if ch.is_ascii_alphanumeric() {
            normalized.push(ch);
            previous_space = false;
        } else if !previous_space {
            normalized.push(' ');
            previous_space = true;
        }
    }
    normalized.trim().to_string()
}

fn find_latest_session_output(
    project_root: &Path,
    run_path: &str,
) -> Result<Option<(String, PathBuf)>> {
    let sessions_dir = project_root.join(run_path).join("sessions");
    if !sessions_dir.is_dir() {
        return Ok(None);
    }

    let mut candidates = Vec::new();
    for entry in fs::read_dir(&sessions_dir)
        .with_context(|| format!("Failed to read {}", sessions_dir.display()))?
    {
        let entry = entry.with_context(|| format!("Failed to read {}", sessions_dir.display()))?;
        if !entry
            .file_type()
            .with_context(|| format!("Failed to inspect {}", entry.path().display()))?
            .is_dir()
        {
            continue;
        }
        let session_id = entry.file_name().to_string_lossy().to_string();
        let output_path = entry.path().join("output.md");
        if output_path.is_file() {
            candidates.push((session_id, output_path));
        }
    }
    candidates.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(candidates.pop())
}

fn git_changed_files(project_root: &Path) -> Option<Vec<String>> {
    let git_repo = Command::new("git")
        .arg("-C")
        .arg(project_root)
        .arg("rev-parse")
        .arg("--is-inside-work-tree")
        .output()
        .ok()?;
    if !git_repo.status.success() {
        return None;
    }

    let mut files =
        run_git_lines(project_root, &["diff", "--name-only", "HEAD", "--"]).unwrap_or_default();
    files.extend(
        run_git_lines(
            project_root,
            &["ls-files", "--others", "--exclude-standard"],
        )
        .unwrap_or_default(),
    );
    files.sort();
    files.dedup();
    Some(files)
}

fn run_git_lines(project_root: &Path, args: &[&str]) -> Option<Vec<String>> {
    let output = Command::new("git")
        .arg("-C")
        .arg(project_root)
        .args(args)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    Some(
        String::from_utf8_lossy(&output.stdout)
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty())
            .map(|line| line.replace('\\', "/"))
            .collect(),
    )
}

fn read_current_phase(project_root: &Path) -> Option<String> {
    let content = fs::read_to_string(project_root.join(".vibehub/state.yaml")).ok()?;
    let value: serde_yaml::Value = serde_yaml::from_str(&content).ok()?;
    value
        .get("current")?
        .get("phase")?
        .as_str()
        .map(|value| value.to_string())
}

fn canonical_project_root(project_root: &Path) -> Result<PathBuf> {
    let project_root = fs::canonicalize(project_root)
        .with_context(|| format!("Project path does not exist: {}", project_root.display()))?;
    if !project_root.is_dir() {
        return Err(anyhow!(
            "Project path is not a directory: {}",
            project_root.display()
        ));
    }
    if !project_root.join(".vibehub").is_dir() {
        return Err(anyhow!(
            "VibeHub directory does not exist: {}",
            project_root.join(".vibehub").display()
        ));
    }
    Ok(project_root)
}

fn relative_to_project(project_root: &Path, target: &Path) -> Result<PathBuf> {
    target
        .strip_prefix(project_root)
        .map(PathBuf::from)
        .with_context(|| format!("Path escapes project root: {}", target.display()))
}

fn normalize_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn title_case(value: &str) -> String {
    value
        .split(['_', '-', ' '])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::vibehub::current::{write_current_run_pointer, write_current_task_pointer};
    use uuid::Uuid;

    fn temp_project() -> PathBuf {
        let path = std::env::temp_dir().join(format!("vibehub-handoff-test-{}", Uuid::new_v4()));
        fs::create_dir_all(path.join(".vibehub/tasks/T-001/runs/R-001/sessions/S-001"))
            .expect("create session");
        fs::create_dir_all(path.join(".vibehub/agent-view")).expect("create agent view");
        fs::write(
            path.join(".vibehub/state.yaml"),
            "current:\n  phase: implement\n",
        )
        .expect("write state");
        write_current_task_pointer(&path, "T-001").expect("task pointer");
        write_current_run_pointer(&path, "T-001", "R-001").expect("run pointer");
        path
    }

    fn write_complete_output(project: &Path) {
        fs::write(
            project.join(".vibehub/tasks/T-001/runs/R-001/sessions/S-001/output.md"),
            r#"# Session Output

## Completed
- Implemented handoff builder.

## Not Yet Done
- Wire GUI status later.

## Key Decisions Made
- Use Git status for changed files when available.

## Files Changed
- agent reported file should be replaced when Git is available.

## Files Reportedly Read
- AGENTS.md
- dev_docs/dev-roadmap.md

## Context Still Needed
- None.

## Warnings
- Runtime observation is not available.

## Next Session Should
1. Review generated handoff.
"#,
        )
        .expect("write output");
    }

    #[test]
    fn builds_handoff_from_latest_output_and_reports_missing_sections() {
        let project = temp_project();
        fs::write(
            project.join(".vibehub/tasks/T-001/runs/R-001/sessions/S-001/output.md"),
            "## Completed\n- Done.\n\n## Next Session Should\n- Continue.\n",
        )
        .expect("write output");

        let result = build_handoff(&project).expect("build handoff");
        let handoff =
            fs::read_to_string(project.join(".vibehub/agent-view/handoff.md")).expect("read");

        assert!(!result.complete);
        assert!(result
            .missing_required_sections
            .contains(&"Key Decisions Made".to_string()));
        assert!(handoff.contains("## Missing Required Sections"));
        assert!(handoff.contains("- Missing from output.md: Key Decisions Made"));

        fs::remove_dir_all(project).expect("cleanup");
    }

    #[test]
    fn git_status_supplies_hard_observed_changed_files_when_available() {
        let project = temp_project();
        write_complete_output(&project);
        Command::new("git")
            .arg("-C")
            .arg(&project)
            .arg("init")
            .output()
            .expect("git init");
        fs::write(project.join("src.rs"), "changed\n").expect("write changed file");

        let result = build_handoff(&project).expect("build handoff");
        let handoff =
            fs::read_to_string(project.join(".vibehub/agent-view/handoff.md")).expect("read");

        assert!(result.complete);
        assert_eq!(result.files_changed_evidence, "hard_observed");
        assert!(handoff.contains("- src.rs"));
        assert!(handoff.contains("Evidence grade: hard_observed"));

        fs::remove_dir_all(project).expect("cleanup");
    }
}
